<Workspace Version="1.3.2.2480" X="-2.7322909887647" Y="122.772132561308" zoom="0.602966259102532" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="32aeae77-2181-4e52-b52b-3f22ea390c9d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="631.035541024576" y="526.800442506836" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import sys
sys.path.append('C:\Program Files (x86)\IronPython 2.7\Lib')
import System
from System import Array
from System.Collections.Generic import *

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference("RevitAPI")
clr.AddReference("RevitAPIUI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Transaction
from Autodesk.Revit.UI.Selection import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
uidoc = uiapp.ActiveUIDocument
app = uiapp.Application

refresh = IN[0]
element_ids = []
elements = []

if refresh == True or refresh == False:
	selection = uidoc.Selection
	reference = selection.PickObject(ObjectType.Element, "Select Element to Delete")
	
	deleted_ids = list([ElementId])
	
	#We begin, then roll-back the transaction
	t = Transaction(doc, 'Name')
	t.Start()
	deleted_ids = doc.Delete(reference.ElementId)
	t.RollBack()
	
	if not t.HasEnded:
		t.Dispose()	
	string = "Object Selected: {}".format(reference.ElementId)

#Formatting a list of Element IDs the way Revit accepts them
for id in deleted_ids:
	element_ids.append(id.ToString())

for deleted_id in deleted_ids:
	elements.append(doc.GetElement(deleted_id))

OUT = string, elements, ";".join(element_ids)</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.BoolSelector guid="d3e46c89-e8b2-49a8-8ca9-5ea02c918432" type="CoreNodeModels.Input.BoolSelector" nickname="Refresh" x="458" y="526.800442506836" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>False</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="590b0adf-7eb4-4755-8101-3d6f549ddf2c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="796.103425647267" y="531.132068987877" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <CoreNodeModels.Watch guid="89ac4854-af3d-41de-9513-1cf3e6e048d2" type="CoreNodeModels.Watch" nickname="Watch" x="1039.84495701966" y="1082.50802240874" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="417195a9-09f6-476e-8c24-1d957bafaaf0" type="CoreNodeModels.Watch" nickname="Watch" x="1039.84495701966" y="294.358008365288" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="89bdbd23-2cd3-4727-982d-8e7e3da2398f" type="CoreNodeModels.Watch" nickname="Watch" x="1039.84495701966" y="544.45725997094" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="32aeae77-2181-4e52-b52b-3f22ea390c9d" start_index="0" end="590b0adf-7eb4-4755-8101-3d6f549ddf2c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d3e46c89-e8b2-49a8-8ca9-5ea02c918432" start_index="0" end="32aeae77-2181-4e52-b52b-3f22ea390c9d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="590b0adf-7eb4-4755-8101-3d6f549ddf2c" start_index="0" end="417195a9-09f6-476e-8c24-1d957bafaaf0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="590b0adf-7eb4-4755-8101-3d6f549ddf2c" start_index="1" end="89bdbd23-2cd3-4727-982d-8e7e3da2398f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="590b0adf-7eb4-4755-8101-3d6f549ddf2c" start_index="2" end="89ac4854-af3d-41de-9513-1cf3e6e048d2" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="6ecbd984-7379-4270-9c12-3b0ecdec2a7f" text="This list is pre-formatted to enable easy transferral to Revit's 'Select By ID' tool." x="1044.4789036236" y="1013.14460236193" />
    <Dynamo.Graph.Notes.NoteModel guid="d108ada4-3f7b-4584-b72a-6d1bb846eca8" text="Any elements which would be deleted, if you deleted the selected element." x="1041.90363422986" y="493.214915440678" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="bb7449bf-63e3-4185-b7d0-2423fc6807f3" annotationText="Formatted Element ID List" left="1029.84495701966" top="931.14460236193" width="310.63394660394" height="260.36342004681" fontSize="30" InitialTop="1013.14460236193" InitialHeight="139" TextblockHeight="72" backgrouund="#FFD8D8D8">
      <Models ModelGuid="89ac4854-af3d-41de-9513-1cf3e6e048d2" />
      <Models ModelGuid="6ecbd984-7379-4270-9c12-3b0ecdec2a7f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="4c4cd799-f841-4c8d-981d-7353c99b63db" annotationText="Selected Element Id" left="1029.84495701966" top="212.358008365288" width="214" height="191" fontSize="30" InitialTop="294.358008365288" InitialHeight="139" TextblockHeight="72" backgrouund="#FFD8D8D8">
      <Models ModelGuid="417195a9-09f6-476e-8c24-1d957bafaaf0" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="56172fba-6f87-44b2-9584-f16973b0979f" annotationText="Elements which would be deleted" left="1029.84495701966" top="411.214915440678" width="322.0586772102" height="511.242344530262" fontSize="30" InitialTop="493.214915440678" InitialHeight="193.363420046809" TextblockHeight="72" backgrouund="#FFD8D8D8">
      <Models ModelGuid="89bdbd23-2cd3-4727-982d-8e7e3da2398f" />
      <Models ModelGuid="d108ada4-3f7b-4584-b72a-6d1bb846eca8" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0fc681a2-e6e8-43d0-a25a-221e71bf5524" annotationText="Toggle to Refresh Selection" left="448" top="408.800442506836" width="149" height="186" fontSize="30" InitialTop="526.800442506836" InitialHeight="98" TextblockHeight="108" backgrouund="#FFD8D8D8">
      <Models ModelGuid="d3e46c89-e8b2-49a8-8ca9-5ea02c918432" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="d1a130f0-484e-46b7-80b7-72748cb534c2" annotationText="Pre-Deletes Element" left="621.035541024576" top="480.800442506836" width="275.067884622691" height="171.331626481041" fontSize="30" InitialTop="526.800442506836" InitialHeight="155.331626481041" TextblockHeight="36" backgrouund="#FFD8D8D8">
      <Models ModelGuid="32aeae77-2181-4e52-b52b-3f22ea390c9d" />
      <Models ModelGuid="590b0adf-7eb4-4755-8101-3d6f549ddf2c" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-13.8021488189697" eyeY="123.895095825195" eyeZ="28.2713432312012" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>