<Workspace Version="1.3.1.1736" X="2434.74295325177" Y="-1053.27224410278" zoom="1.41492105157213" ScaleFactor="100" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.BoolSelector guid="6703b6e1-928a-405f-8f6e-d255caa20fee" type="CoreNodeModels.Input.BoolSelector" nickname="restart" x="-1539.5122323622" y="1023.90294907062" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Nodes.DSModelElementsSelection guid="178e3fa9-61e4-4e6f-a2bc-48b6e31a14fb" type="Dynamo.Nodes.DSModelElementsSelection" nickname="Select Model Elements" x="-1669.62573441289" y="863.335822104091" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="b5c01c7d-c1a0-498e-882b-60fb13e66af4-00045687" />
      <instance id="b5c01c7d-c1a0-498e-882b-60fb13e66af4-00045699" />
      <instance id="b5c01c7d-c1a0-498e-882b-60fb13e66af4-000456eb" />
      <instance id="b5c01c7d-c1a0-498e-882b-60fb13e66af4-000457ce" />
    </Dynamo.Nodes.DSModelElementsSelection>
    <PythonNodeModels.PythonNode guid="15da3828-88e8-4957-a709-b91de4c60853" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-1332.93680199363" y="916.799602449373" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference('ProtoGeometry')
#from Autodesk.DesignScript.Geometry import *
import Autodesk.DesignScript.Geometry as ge # ИБО КОНФЛИКТ REFERENCE !!!!!!!!

doc = DocumentManager.Instance.CurrentDBDocument 

walls=[]
grids=[]
lengths=[]
inc = 304.8
for i in IN[0]:
	typename = i.GetType().Name
	if typename == "Wall":
		walls.append(i)
		lengths.append(UnwrapElement(i).Location.Curve.Length * 304.8)
	elif typename == "Grid":
		grids.append(i)

for i in walls:
	if (UnwrapElement(i).Location.Curve.Length * 304.8) == min(lengths):
		shortWall = i


curve = UnwrapElement(shortWall).Location.Curve.ToProtoType()
pt0=curve.PointAtParameter(0.5)
x0 = curve.PointAtParameter(0).X
x1 = curve.PointAtParameter(1).X
y0 = curve.PointAtParameter(0).Y
y1 = curve.PointAtParameter(1).Y
if abs(y0-y1)&lt;10:
	pt1= ge.Point.ByCoordinates(pt0.X, pt0.Y+1000, pt0.Z)
	line= ge.Line.ByStartPointEndPoint(pt0,pt1).ToRevitType()
elif abs(x0-x1)&lt;10:
	pt1= ge.Point.ByCoordinates(pt0.X+1000, pt0.Y, pt0.Z)
	line= ge.Line.ByStartPointEndPoint(pt0,pt1).ToRevitType()


walls = UnwrapElement(walls)
grids = UnwrapElement(grids)
Ref = ReferenceArray()
opt = Options()
opt.ComputeReferences = True
opt.IncludeNonVisibleObjects = True
opt.View = doc.ActiveView

for grid in grids:
	for obj in grid.get_Geometry(opt):
		if isinstance(obj, Line):
			gline = obj
			Ref.Append(gline.Reference)
		
for element in walls:
	a = HostObjectUtils.GetSideFaces(element, ShellLayerType.Exterior)
	for i in a:
		Ref.Append(i)
	b = HostObjectUtils.GetSideFaces(element, ShellLayerType.Interior)
	for i in b:
		Ref.Append(i)

TransactionManager.Instance.EnsureInTransaction(doc)

newdim = doc.Create.NewDimension(doc.ActiveView, line, Ref).ToDSType(False)

TransactionManager.Instance.TransactionTaskDone()
OUT=newdim
</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6703b6e1-928a-405f-8f6e-d255caa20fee" start_index="0" end="15da3828-88e8-4957-a709-b91de4c60853" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="178e3fa9-61e4-4e6f-a2bc-48b6e31a14fb" start_index="0" end="15da3828-88e8-4957-a709-b91de4c60853" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>